In [1]:
from typing import List, Tuple, Dict, Union
import numpy as np

In [7]:
rates = {
    'p':  {'p':1,    'w': 0.48, 's': 1.52, 'sh': 0.71},
    'w':  {'p':2.05, 'w': 1,    's': 3.26, 'sh': 1.56},
    's':  {'p':0.64, 'w': 0.3,  's': 1,    'sh': 0.46},
    'sh': {'p':1.41, 'w': 0.61, 's': 2.08, 'sh': 1   },
}

product_list = [product for product in rates.keys()]

def traverse(path: List[Union[None, Tuple[str, str]]]) -> List[List[Tuple[str, str]]]:
    start = 'sh' if len(path) == 0 else path[-1][-1]

    if len(path) == 4:
        path.append((path[-1][-1], 'sh'))
        return [path]
    else:
        path_collection = []
        for product in product_list:
            path_next = [element for element in path] + [(start, product)]
            path_collection += traverse(path_next)
        return path_collection

path_list = traverse([])

In [8]:
profit_list = []
for path in path_list:
    path_rate = 1
    for transition in path:
        start = transition[0]
        to = transition[1]
        path_rate *= rates[start][to]
    profit_list.append(path_rate)

max_idx = np.argsort(profit_list)[-1]
ascending_rank = np.sort(profit_list)
path_list[max_idx]

[('sh', 'p'), ('p', 'w'), ('w', 'sh'), ('sh', 'p'), ('p', 'sh')]

In [9]:
ascending_rank[-5:]

array([1.055808  , 1.055808  , 1.055808  , 1.05696939, 1.05696939])

In [11]:
rates = {
    'p':  {'p':1,    'w': 0.48, 's': 1.52, 'sh': 0.71},
    'w':  {'p':2.05, 'w': 1,    's': 3.26, 'sh': 1.56},
    's':  {'p':0.64, 'w': 0.3,  's': 1,    'sh': 0.46},
    'sh': {'p':1.41, 'w': 0.61, 's': 2.08, 'sh': 1   },
}

product_list = [product for product in rates.keys()]

def traverse(path: List[Union[None, Tuple[str, str]]]) -> List[List[Tuple[str, str]]]:
    start = 'sh' if len(path) == 0 else path[-1][-1]

    if len(path) == 3:
        path.append((path[-1][-1], 'sh'))
        return [path]
    else:
        path_collection = []
        for product in product_list:
            path_next = [element for element in path] + [(start, product)]
            path_collection += traverse(path_next)
        return path_collection

path_list = traverse([])

profit_list = []
for path in path_list:
    path_rate = 1
    for transition in path:
        start = transition[0]
        to = transition[1]
        path_rate *= rates[start][to]
    profit_list.append(path_rate)

max_idx = np.argsort(profit_list)[-1]
ascending_rank = np.sort(profit_list)
path_list[max_idx]

[('sh', 'sh'), ('sh', 'p'), ('p', 'w'), ('w', 'sh')]

In [12]:
ascending_rank[-5:]

array([1.01492928, 1.055808  , 1.055808  , 1.055808  , 1.055808  ])

In [13]:
rates = {
    'p':  {'p':1,    'w': 0.48, 's': 1.52, 'sh': 0.71},
    'w':  {'p':2.05, 'w': 1,    's': 3.26, 'sh': 1.56},
    's':  {'p':0.64, 'w': 0.3,  's': 1,    'sh': 0.46},
    'sh': {'p':1.41, 'w': 0.61, 's': 2.08, 'sh': 1   },
}

product_list = [product for product in rates.keys()]

def traverse(path: List[Union[None, Tuple[str, str]]]) -> List[List[Tuple[str, str]]]:
    start = 'sh' if len(path) == 0 else path[-1][-1]

    if len(path) == 2:
        path.append((path[-1][-1], 'sh'))
        return [path]
    else:
        path_collection = []
        for product in product_list:
            path_next = [element for element in path] + [(start, product)]
            path_collection += traverse(path_next)
        return path_collection

path_list = traverse([])

profit_list = []
for path in path_list:
    path_rate = 1
    for transition in path:
        start = transition[0]
        to = transition[1]
        path_rate *= rates[start][to]
    profit_list.append(path_rate)

max_idx = np.argsort(profit_list)[-1]
ascending_rank = np.sort(profit_list)
path_list[max_idx]

[('sh', 'p'), ('p', 'w'), ('w', 'sh')]

In [14]:
ascending_rank[-5:]

array([1.      , 1.0011  , 1.0011  , 1.0011  , 1.055808])

In [15]:
rates = {
    'p':  {'p':1,    'w': 0.48, 's': 1.52, 'sh': 0.71},
    'w':  {'p':2.05, 'w': 1,    's': 3.26, 'sh': 1.56},
    's':  {'p':0.64, 'w': 0.3,  's': 1,    'sh': 0.46},
    'sh': {'p':1.41, 'w': 0.61, 's': 2.08, 'sh': 1   },
}

product_list = [product for product in rates.keys()]

def traverse(path: List[Union[None, Tuple[str, str]]]) -> List[List[Tuple[str, str]]]:
    start = 'sh' if len(path) == 0 else path[-1][-1]

    if len(path) == 1:
        path.append((path[-1][-1], 'sh'))
        return [path]
    else:
        path_collection = []
        for product in product_list:
            path_next = [element for element in path] + [(start, product)]
            path_collection += traverse(path_next)
        return path_collection

path_list = traverse([])

profit_list = []
for path in path_list:
    path_rate = 1
    for transition in path:
        start = transition[0]
        to = transition[1]
        path_rate *= rates[start][to]
    profit_list.append(path_rate)

max_idx = np.argsort(profit_list)[-1]
ascending_rank = np.sort(profit_list)
path_list[max_idx]

[('sh', 'p'), ('p', 'sh')]

In [16]:
ascending_rank[-5:]

array([0.9516, 0.9568, 1.    , 1.0011])